/**
 * Photo registry: curated recorrido placement, a per-photo number (archive
 * index) and a per-photo caption.
 *
 * Each PHOTO_TEXT value holds TWO paragraphs separated by "||": the left detail
 * column (what you see) and the right one (what it means). The recorrido side
 * column uses only the first sentence (leadFor).
 *
 * To CHANGE a recorrido photo: edit its id in APARTADO_PHOTOS (+ its text below).
 * Ids = manifest ids (ver public/img/manifest.json).
 */

export const APARTADO_PHOTOS = {
  'EL ORIGEN': ['img-0357', 'img-0485', 'img-0334', 'img-0323', 'img-0028'],
  'EL UMBRAL': [
    'alberche-whatsapp-image-2026-06-06-at-15-30-20',
    'alberche-whatsapp-image-2026-06-06-at-15-30-20a',
    '20260412-113341',
    'img-0360',
    'alberche-whatsapp-image-2026-06-06-at-15-22-27',
  ],
  'EL CAUCE': [
    'img-0282', 'img-0169', 'img-0309',
    'alberche-whatsapp-image-2026-06-06-at-15-26-45', 'img-0377',
  ],
  'DESENLACE': ['img-0229', 'img-0358', 'img-0456', 'img-0131', 'img-0364'],
};

export const ARCHIVE = [
  ...Object.values(APARTADO_PHOTOS).flat(),
  'hero-background-hero',
  'intro-vertical-1', 'intro-vertical-2', 'intro-horizontal-3', 'intro-horizontal-4',
  'intro-horizontal-5', 'intro-vertical-6', 'intro-horizontal-7',
  'expolozoya-horizontal-1', 'expolozoya-horizontal-2', 'expolozoya-vertical-3',
  'expolozoya-vertical-4', 'expolozoya-horizontal-5', 'expolozoya-horizontal-6',
  'expoalberche-vertical-1', 'expoalberche-horizontal-2', 'expoalberche-horizontal-3',
  'expoalberche-vertical-4', 'expoalberche-horizontal-5', 'expoalberche-horizontal-6',
  'alberche-whatsapp-image-2026-06-06-at-15-17-28',
  'alberche-whatsapp-image-2026-06-06-at-15-19-24',
  'alberche-whatsapp-image-2026-06-06-at-15-30-20d',
  'alberche-whatsapp-image-2026-06-06-at-15-31-44-copia',
  'alberche-whatsapp-image-2026-06-06-at-15-31-44',
  'alberche-whatsapp-imagea-2026-06-06-at-15-26-45',
  'img-0046', 'img-0132', 'img-0137', 'img-0146', 'img-0156', 'img-0172',
  'img-0240', 'img-0264', 'img-0281', 'img-0285', 'img-0287', 'img-0307',
  'img-0365', 'img-0405', 'img-0468',
];

export const TOTAL = ARCHIVE.length;

export const PHOTO_TEXT = {
  /* ---------- EL ORIGEN ---------- */
  'img-0357': 'El núcleo urbano marca el origen de la presión: donde el hombre se asienta, el río deja de ser solo río. Las fachadas se asoman al agua como si pudieran beberla, ordenadas en hileras que dan la espalda al monte. La piedra labrada sustituye poco a poco a la ribera, y el rumor del pueblo se mezcla con el de la corriente. Es el primer punto del recorrido en que algo construido pesa más que el paisaje. || El cauce empieza a llevar, disuelto e invisible, todo lo que el núcleo le entrega sin darse cuenta. TRUTTA abre aquí su expediente, en la frontera exacta entre la piedra habitada y la corriente que la ignora. No se trata de condenar el asentamiento, sino de medir su huella con precisión normativa. El origen del relato es este instante en que el agua deja de pertenecerse solo a sí misma.',
  'img-0485': 'Un pueblo cosido al cauce, casa contra casa, contra el agua, sin apenas margen entre el tejado y la orilla. Es la primera huella humana del recorrido, todavía contenida, sobre un río que aún corre limpio. Las construcciones se apiñan buscando el agua, como han hecho durante siglos en toda la España interior. El conjunto resume, en un solo plano, la vieja dependencia entre el hombre y el río. || Aquí arranca formalmente el archivo, en el punto donde empieza a haber algo que vigilar. Documentar este lugar es fijar el antes —el origen— de todo lo que vendrá aguas abajo, antes de que la presión se acumule. El pueblo no es el enemigo: es el testigo más antiguo del río y, a la vez, su primera amenaza. Por eso encabeza el expediente, con fecha y con nombre.',
  'img-0334': 'La fuente del pueblo: el agua domesticada, canalizada, puesta al servicio del núcleo habitado. Lo que en el río es corriente libre, aquí es caño, pilón y turno medido. La piedra encauza el agua, la detiene, la ofrece a quien la necesite a cambio de obediencia. Es el gesto fundacional de toda intervención: retener para servirse. || El origen de la presión no es un vertido ni una obra, sino esta voluntad antigua de domesticar el agua. Hacerla parar, aunque sea un instante, ya es empezar a poseerla. Cada caño abierto es un pequeño contrato entre el pueblo y el río, casi siempre desigual. TRUTTA documenta ese contrato para recordar sus cláusulas, las que nadie suele leer.',
  'img-0323': 'Arquitectura a pie de río, levantada con la espalda recta frente a la corriente. El edificio mira al agua; el agua, indiferente, sigue su camino sin devolverle la mirada. La piedra permanece, fija, mientras todo lo demás del encuadre se mueve. En ese contraste se condensa la relación entre lo humano y lo fluvial. || El origen de TRUTTA es precisamente esta tensión entre lo que permanece y lo que no se detiene nunca. La construcción aspira a durar; el río ya dura, sin proponérselo, desde mucho antes. Entre lo fijo y lo que fluye se abre el desencuentro que da pie al relato. Documentarlo es tomar nota de quién llegó primero, y quién seguirá cuando el otro falte.',
  'img-0028': 'La infraestructura cruza el valle y lo ordena a su manera, con líneas rectas donde la naturaleza solo había puesto curvas. La obra impone su geometría sobre un paisaje que funcionaba bien sin ella. Su trazado es eficiente, calculado, ajeno a la pendiente y al meandro. Marca, a la vista de todos, hasta dónde llega la mano del hombre. || El origen del recorrido es esa imposición, ese momento en que el cálculo se superpone al cauce. Bajo la obra, el río continúa su trazado anterior, más viejo que cualquier proyecto y más paciente que cualquier hormigón. La estructura cuenta los años en décadas; el agua, en milenios. TRUTTA registra ambas cronologías para que no se confunda lo reciente con lo permanente.',

  /* ---------- EL UMBRAL ---------- */
  'alberche-whatsapp-image-2026-06-06-at-15-30-20': 'El puente: umbral entre orillas, una estructura que se posa sobre el cauce sin llegar a detenerlo. Sus pilas se hunden en el agua, pero la corriente las rodea y sigue. Une dos lados que antes solo el vado conectaba, y al hacerlo cambia el ritmo del lugar. Es la primera obra del recorrido que convive con el río sin secuestrarlo. || Por debajo, el agua mantiene su negociación de siglos con la piedra, puliéndola despacio. Cruzar el puente es franquear un límite humano; el río, mientras tanto, no reconoce ninguno. El umbral es esta frontera tendida en el aire, que separa sin cerrar. TRUTTA la documenta como ejemplo de equilibrio: presencia humana que no ahoga, solo acompaña.',
  'alberche-whatsapp-image-2026-06-06-at-15-30-20a': 'Cruzar el agua sin tocarla: esa es la promesa del puente, y también su pequeña mentira. La estructura se tiende sobre la corriente como una tregua de piedra entre las dos orillas. Bajo el arco, el agua sigue indiferente, llevándose hojas, luz y tiempo. El paso humano queda arriba; la vida del río, abajo. || El umbral es este punto en que lo que se queda y lo que pasa comparten el mismo encuadre sin mezclarse. Aguas abajo, todo lo que el puente separó vuelve a juntarse, ajeno a la obra. La construcción cree dividir el río; en realidad solo lo sobrevuela un instante. TRUTTA anota esa modestia involuntaria de la piedra frente a la corriente.',
  '20260412-113341': 'Obra y río comparten valle, obligados a entenderse en el mismo plano. La estructura impone su geometría recta; el agua opone su paciencia curva. Ninguna de las dos cede del todo, y de esa tirantez nace el paisaje. El umbral es justo ese pulso, sostenido y silencioso. || En esta franja, lo construido y lo vivo se miden de cerca, sin tocarse del todo. Gana, a la larga, lo que dura más, y el río lleva aquí mucho más tiempo que el cemento. La obra envejecerá, se agrietará, será sustituida; la corriente seguirá pasando. TRUTTA documenta el momento exacto en que ambos coexisten, antes de que uno se imponga al otro.',
  'img-0360': 'El muro contiene el agua y, al contenerla, la convierte en otra cosa. Umbral absoluto: aquí el río se detiene a voluntad humana, se acumula, se mide en metros y en megavatios. Lo que era prisa se vuelve lámina quieta, vigilada por compuertas. La corriente pierde su nombre y pasa a llamarse reserva. || Lo que entra como río sale como recurso, si es que vuelve a salir con la misma vida. Detener un cauce es la forma más rotunda de poseerlo, de decidir cuándo y cuánto fluye. El embalse no es un crimen, pero sí una frontera, y toda frontera merece registro. TRUTTA la documenta como el umbral más extremo del recorrido: donde el río deja, literalmente, de correr.',
  'alberche-whatsapp-image-2026-06-06-at-15-22-27': 'El embalse: un río convertido en estructura, una lámina quieta donde antes había prisa. El agua se extiende mansa entre laderas, ocupando lo que fue valle y cauce. La superficie refleja el cielo con una calma que no es natural, sino administrada. Es el umbral donde la corriente se vuelve depósito. || Bajo esa quietud, el agua espera su turno para volver a ser río, aguas abajo del muro. La paciencia del embalse es impuesta, no elegida: el río está retenido, no en paz. Contener no es lo mismo que conservar, y esa diferencia es justo lo que TRUTTA vigila. El expediente anota la calma, pero también la fecha en que dejó de fluir libre.',

  /* ---------- EL CAUCE ---------- */
  'img-0282': 'Solo cauce. El río ocupa el plano entero, sin orillas que lo expliquen ni contexto que lo suavice. No hay monte, ni puente, ni pueblo: hay agua moviéndose de borde a borde. La imagen renuncia a todo lo accesorio para quedarse con lo esencial. Es el río en estado puro, sin coartada. || Es agua y nada más: la sustancia básica, desplazándose porque no sabe hacer otra cosa. Aquí el archivo deja de narrar y simplemente mira, sin adjetivos. La pureza no necesita relato; le basta con mostrarse. TRUTTA documenta este tramo como recordatorio de qué es, exactamente, lo que está en juego: el agua misma.',
  'img-0169': 'Agua en movimiento de un lado a otro del encuadre, ocupando casi todo el plano. El cauce es el protagonista absoluto; la cámara apenas le sigue el paso. La superficie se pliega, brilla y avanza sin descanso, indiferente al objetivo. No hay orilla que distraiga: solo corriente. || Cada metro de esa superficie transporta oxígeno, temperatura e información química precisa. La trucha la lee mejor que cualquier instrumento, y su veredicto es inapelable. Donde el río se mueve así de limpio y constante, el diagnóstico se firma solo. TRUTTA se limita a registrar lo que el agua ya certifica con su propio movimiento.',
  'img-0309': 'El río se ensancha y lo llena todo, generoso, sin estrechez ni urgencia. La corriente se relaja, se extiende de lado a lado y respira con holgura. No hay rápidos ni obstáculos, solo una lámina ancha que avanza serena. Aquí el cauce se basta a sí mismo, sin necesidad de contexto. || Documentar este tramo es certificar que, en algún sitio, el agua todavía puede ser solo agua. Sin función asignada, sin dueño, sin más misión que seguir bajando hacia el mar. Esa gratuidad —un río que no sirve para nada y por eso vale tanto— es lo que el archivo defiende. TRUTTA lo anota como prueba de que la pureza, a veces, no exige nada a cambio.',
  'alberche-whatsapp-image-2026-06-06-at-15-26-45': 'Superficie viva. El cauce respira en cada rizo: luz arriba, oxígeno disuelto debajo, frío constante en el fondo. La corriente se riza sin parar, dibujando una piel inquieta sobre el agua. Lo que parece quietud es, de cerca, puro trabajo. El río no descansa nunca. || Bajo esa superficie, el agua se oxigena, se depura y se mantiene a la altura de su habitante más exigente. Cada movimiento incorpora aire, cada metro renueva el frío que la trucha necesita. Parar sería empezar a enfermar; por eso el cauce insiste en moverse. TRUTTA documenta esa respiración continua como el signo vital más básico de un río sano.',
  'img-0377': 'Piedra bajo agua clara: el cauce enseña su lecho sin pudor, como quien no tiene nada que ocultar. Cada canto del fondo se ve nítido a través de la corriente. La transparencia no es un adorno: es un dato. Donde se ve el fondo, el agua está limpia. || Cada piedra sumergida es prueba de oxigenación, de ausencia de contaminantes, de un equilibrio que nadie ha roto todavía. La claridad del agua funciona como un certificado que no se puede falsificar. Basta mirar para saber; el río se autoinspecciona a la luz. TRUTTA solo tiene que apuntar lo que el agua ya muestra: que sigue siendo, milímetro a milímetro, agua de verdad.',

  /* ---------- DESENLACE ---------- */
  'img-0229': 'El otoño tiñe la ribera y anuncia el final del ciclo. El río se acerca a su desenlace entre el color, más lento, más ancho, más cansado. Las hojas caen sobre la corriente y se dejan llevar sin resistencia. Todo en la escena sugiere cierre, descanso, despedida. || Lo que fue origen urbano y umbral construido es aquí, por fin, solo paisaje que se apaga. El recorrido se cierra con la misma dignidad con que las hojas se sueltan de la rama. No hay drama en este final, solo aceptación del ritmo de las cosas. TRUTTA documenta el desenlace como lo que es: no una muerte, sino el cumplimiento natural de un trayecto.',
  'img-0358': 'Islas y meandros: el río se reparte, se ramifica, se despide en varias direcciones a la vez. La corriente principal se deshace en brazos que rodean bancos de tierra y vegetación. El cauce, antes único, se vuelve plural y disperso. Es el agua soltando, por fin, la tensión de su recorrido. || El desenlace no es un punto sino una dispersión, una entrega del río a sus propios afluentes y derivaciones. Cada brazo se lleva una parte del relato hacia su propio final, sin prisa. Lo que empezó como una línea clara termina como un delta de posibilidades. TRUTTA documenta esa ramificación como la forma más serena de acabar: no cerrándose, sino abriéndose.',
  'img-0456': 'Verde y agua en calma. El desenlace es esta naturaleza que, contra todo pronóstico y toda obra, sobrevive. La vegetación abraza la orilla y el agua descansa, sin rastro de prisa ni de presión. La escena respira una salud que parece fácil pero no lo es. Es la recompensa de todo el recorrido. || Donde el hombre apretó, el río aflojó; donde lo contuvieron, encontró el modo de seguir. Aquí respira, intacto, lo que estuvimos a punto de perder por descuido o por exceso. Este verde no es decorado: es la prueba de que la conservación funciona cuando se la deja funcionar. TRUTTA cierra el expediente con esta imagen, como quien guarda lo más valioso para el final.',
  'img-0131': 'Niebla sobre el agua: el fin del río se disuelve en el paisaje, sin frontera clara. La bruma borra los límites entre el cauce, la orilla y el cielo. Dónde acaba el agua y dónde empieza el aire ya no importa demasiado. Todo se funde en una misma materia gris y serena. || El desenlace es esta indistinción, esta renuncia del río a marcar dónde termina. El archivo se cierra como se cierra un cauce: no con un punto, sino difuminándose hasta que ya no se sabe dónde estaba. La niebla no oculta el final; lo suaviza. TRUTTA documenta esa disolución como la última lección del río: acabar sin estridencia, dejar de verse sin dejar de estar.',
  'img-0364': 'El cauce se funde con el bosque y deja de ser frontera. El río se entrega a la vegetación que lo acompañó todo el camino, hasta confundirse con ella. Los árboles se inclinan sobre el agua y el agua los refleja, sin separación. Ya no hay un límite claro entre lo líquido y lo vivo. || El río ya no separa orillas: las une bajo la misma sombra, como si toda la cuenca fuera una sola cosa. Lo que documentamos en este desenlace es, sencillamente, una reconciliación entre el agua y la tierra. Tras el origen urbano y el umbral construido, el final es un abrazo. TRUTTA lo registra como prueba de que un río bien cuidado no termina: se integra.',

  /* ---------- LANDING · hero + intro ---------- */
  'hero-background-hero': 'El embalse al anochecer, cuando la superficie se vuelve un espejo negro y liso. Bajo esa quietud late un río entero, contenido pero no vencido. La luz se retira y el agua adopta el color de la piedra que la rodea. Todo parece detenido, aunque nada lo esté. || La penumbra iguala el agua y la roca; solo el reflejo recuerda que, abajo, todo sigue en movimiento. La calma de la noche no es ausencia de río: es río guardado, a la espera. Lo que de día sería un paisaje cualquiera, de noche se vuelve un secreto. TRUTTA elige esta hora porque obliga a mirar dos veces antes de entender qué se está viendo.',
  'intro-vertical-1': 'El árbol se asoma a la orilla y se duplica, perfecto, en el agua quieta. Orilla intacta, agua espejada: ni una arruga rompe el reflejo. La vegetación llega justo hasta el borde, sin que nada la haya recortado. Es una imagen de equilibrio difícil de encontrar y fácil de perder. || Donde la ribera sigue viva, el río conserva su sombra, su frescor y su derecho a no ser tocado. Ese árbol no está de adorno: enfría el agua, sujeta la tierra y alimenta el cauce. Un equilibrio que no pide nada y, sin embargo, lo sostiene todo. TRUTTA documenta estos bordes intactos porque son la primera cosa que desaparece cuando llega la presión.',
  'intro-vertical-2': 'El cauce desciende encajado entre la vegetación, sin un hueco por donde mirar el fondo. Verde y agua se entrelazan, sin fisuras, en una franja estrecha y densa. La luz apenas se cuela entre las ramas hasta la corriente. Todo parece sellado, protegido, a salvo. || El bosque protege la corriente y la corriente alimenta el bosque, en un pacto que viene de lejos. Es un acuerdo que ningún plan de ordenación ha sabido mejorar, por mucho que lo intente. Donde el río y su ribera se cuidan así, no hace falta gestionar casi nada. TRUTTA documenta este tramo como modelo: lo que un río necesita es, sobre todo, que lo dejen en paz.',
  'intro-horizontal-3': 'Un tramo cualquiera, un agua única. Sin titular, sin acontecimiento, solo un río haciendo lo que lleva milenios haciendo. No hay nada espectacular que señalar, y ahí está su valor. La normalidad de esta corriente es, hoy, lo más raro. || Así empieza el archivo: por lo ordinario, por lo que casi nadie fotografía. Esta calma sin noticia es, en el siglo de los ríos enfermos, una excepción que merece expediente, fecha y firma. Documentar lo normal es la forma de impedir que se vuelva extraordinario por ausencia. TRUTTA empieza aquí, en el agua que aún no ha pasado nada, precisamente para que no le pase.',
  'intro-horizontal-4': 'Viento sobre el agua: la superficie nunca está dos veces igual. Cada ráfaga reescribe el dibujo de la luz, riza el plano, lo despeina. La imagen parece inestable, cambiante, imposible de fijar. Y, sin embargo, algo permanece constante bajo el desorden. || Debajo de ese ajetreo, la química del río se mantiene fija como una firma. El cauce cambia de cara sin cambiar de salud: la inestabilidad de arriba esconde una fidelidad absoluta. Lo que se mueve es la piel; lo que importa, debajo, no se altera. TRUTTA documenta esta paradoja como prueba de que un río sano puede parecer caótico y ser, en el fondo, de una constancia perfecta.',
  'intro-horizontal-5': 'Roca y corriente. El lecho visible delata aguas limpias: donde se ve la piedra del fondo, no hay turbidez que esconder. La luz atraviesa el agua hasta el último canto. La transparencia ocupa todo el plano, sin matices. Es la imagen más honesta que un río puede ofrecer. || La claridad es la firma del río sano, y este la lleva estampada en cada metro de su recorrido. Mirar el fondo es leer, directamente y sin instrumentos, su estado de salud. Ningún análisis de laboratorio es tan inmediato como esta transparencia. TRUTTA documenta el lecho a la vista porque es, en sí mismo, un certificado que el agua firma a plena luz.',
  'intro-vertical-6': 'Una vertical de río puro, encajada entre laderas que apenas dejan pasar la luz. El cauce desciende estrecho, frío y limpio, sin testigos. La España Vaciada lo guarda en silencio, sin carteles ni audioguías que lo señalen. Está ahí desde siempre, ignorado y, por eso, intacto. || Documentarlo es darle existencia oficial sin convertirlo en destino turístico. El archivo lo nombra precisamente para que nadie sienta que tiene que ir a verlo en persona. La mejor protección de este tramo es seguir siendo anónimo. TRUTTA lo registra con cuidado de no revelar de más: una ficha, no un folleto.',
  'intro-horizontal-7': 'El río sigue su curso, ajeno por completo a quien lo mira desde la orilla. No posa, no espera, no se detiene para la fotografía. Avanza con la misma indiferencia con que lo ha hecho siempre. Registrar sin pisar, mirar sin abrir camino: esa es la consigna. || Documentarlo es, sobre todo, no tocarlo. TRUTTA fotografía precisamente para que no haga falta venir: la imagen sustituye a la visita y, al hacerlo, protege lo que muestra. Cada foto es una manera de estar sin dejar huella. El expediente existe para que el río no tenga que recibir a nadie y, aun así, sea conocido por todos.',

  /* ---------- LANDING · expositor Lozoya ---------- */
  'expolozoya-horizontal-1': 'El Lozoya entre bosque, afluente del Jarama en la Comunidad de Madrid. Baja todavía frío, todavía limpio, entre orillas espesas de vegetación. La sierra le da el agua y la sombra que necesita. Es uno de esos tramos que parecen de otro siglo. || Uno de los últimos refugios de pureza hídrica absoluta de la Península Ibérica. Aquí la trucha común no sobrevive a duras penas: prospera, que es la prueba más exigente de todas. Donde ella se reproduce con holgura, el agua responde por sí sola. TRUTTA documenta el Lozoya como patrón de referencia: el río contra el que medir a todos los demás.',
  'expolozoya-horizontal-2': 'Aguas frías de sierra. El Lozoya nace limpio y exigente, y mantiene esa exigencia tramo a tramo, sin aflojar. Su corriente conserva la temperatura baja y estable de la montaña. No es un río fácil de contentar, y por eso es tan fiable. || Esa temperatura constante y su oxigenación excepcional lo convierten en un laboratorio natural de pureza. Lo que aquí se mide es el patrón con el que juzgar la salud de los demás ríos. El Lozoya no es solo un caso: es la vara con la que se mide. TRUTTA lo documenta con detalle porque sus datos sirven, después, para evaluar cuencas mucho menos afortunadas.',
  'expolozoya-vertical-3': 'El embalse fragmenta el Lozoya en islas, lo contiene y lo vigila desde el muro. El río encajado se vuelve aquí lámina administrada, repartida entre brazos de agua quieta. La sierra sigue alrededor, pero el cauce ya obedece a compuertas. Es el Lozoya con correa. || Aun así, conserva bajo la calma su agua de sierra, fría y limpia, esperando seguir. Contenido no es lo mismo que domado: el Lozoya aguanta, paciente, la oportunidad de recuperar su prisa. La retención lo frena, no lo corrompe. TRUTTA documenta este punto como recordatorio de que incluso el agua más pura puede ser detenida, y de lo que eso significa.',
  'expolozoya-vertical-4': 'El Lozoya encajado entre laderas, buscando la sombra del relieve que lo mantiene fresco. Baja deprisa, frío y oxigenado, sin tiempo material para corromperse. El cauce estrecho lo obliga a moverse rápido. Esa velocidad es, en parte, su salud. || El estrechamiento es su mejor defensa: poca superficie expuesta, poca luz, poco calor. La pureza hídrica a pie de sierra depende menos de la voluntad humana que de esta geografía que lo protege. A veces el mejor guardián de un río es el propio terreno. TRUTTA documenta esa alianza entre el relieve y el agua, que conserva sin que nadie tenga que esforzarse.',
  'expolozoya-horizontal-5': 'El río se ensancha bajo Buitrago del Lozoya, más sereno pero igual de limpio que arriba. La corriente se abre, se calma, refleja el pueblo y la sierra. Sigue siendo agua de montaña, solo que con más holgura. Cada tramo deja constancia de su estado. || Caudal documentado, agua certificada: cada metro entra en el expediente con su fecha y su dato. La trucha firma esa certificación con su sola presencia, sin necesidad de análisis. Donde ella está, el agua responde por sí misma ante cualquier inspección. TRUTTA registra el Lozoya a su paso por Buitrago como muestra de que la pureza puede mantenerse incluso junto al pueblo.',
  'expolozoya-horizontal-6': 'Tramo del Lozoya en calma, sin rápidos ni espuma que lo delaten. El agua avanza despacio, casi sin ruido, entre orillas tranquilas. La quietud podría confundirse con pereza, pero no lo es. Bajo la superficie sigue habiendo frío y movimiento. || La quietud no es estancamiento: el agua sigue fría y viva, oxigenada por debajo. La trucha confirma su salud simplemente quedándose, sin marcharse a buscar mejor sitio. Su permanencia es, en sí misma, el diagnóstico más fiable. TRUTTA documenta esta calma para distinguirla del agua muerta: aquí lo tranquilo está vivo, y eso hay que saber leerlo.',

  /* ---------- LANDING · expositor Alberche ---------- */
  'expoalberche-vertical-1': 'El cauce vertical del Alberche, encajado, buscando la sombra del relieve que lo refresca. Baja frío desde Gredos sin perder pureza por el camino. Las laderas lo aprietan y lo protegen a la vez. Es un río de montaña que conserva su carácter aguas abajo. || Afluente del Tajo entre Ávila y Toledo, recorre tierras secas sin contagiarse de su sequedad. El estrechamiento lo protege de la luz y del calor, que son sus peores enemigos. La geografía hace aquí el trabajo de conservación que en otros sitios falta. TRUTTA documenta cómo el propio terreno, sin intervención humana, mantiene limpio al Alberche en su tramo alto.',
  'expoalberche-horizontal-2': 'El Alberche tendido bajo la sierra, afluente del Tajo entre Ávila y Toledo. Laderas peladas arriba, agua fría abajo: el contraste salta a la vista. La tierra reseca enmarca una corriente que se niega a secarse. El paisaje parece negarle el agua, y aun así el río la lleva. || Donde el entorno se agosta, el Alberche insiste en seguir vivo, fresco y en movimiento. Esa insistencia, terca, es justo lo que el archivo viene a registrar. Un río que sobrevive en tierra dura demuestra más salud que uno mimado por el clima. TRUTTA documenta ese contraste porque, cuanto más hostil es el marco, más valioso resulta el agua que aún corre limpia.',
  'expoalberche-horizontal-3': 'Laderas secas, agua fría: el contraste que define al Alberche en todo su recorrido. El río atraviesa una tierra que parece haberle dado la espalda. Alrededor, el matorral reseco; en el centro, la corriente intacta. La imagen resume su carácter de superviviente. || Y, sin embargo, el agua baja limpia, sin rastro del polvo que la rodea. Esa terquedad —seguir siendo río en mitad de la sequedad— es su mejor certificado de salud. No le hace falta un entorno amable para conservarse: le basta con la pendiente y el frío. TRUTTA documenta esta resistencia como prueba de que la pureza no depende solo del paisaje, sino del propio empeño del cauce.',
  'expoalberche-vertical-4': 'Detalle de superficie: la luz fría sobre el agua del Alberche, rizada por la corriente. El plano se cierra sobre el agua misma, sin orilla ni cielo. Cada onda atrapa un reflejo distinto. En ese pequeño fragmento se concentra todo el río. || En el rizo de la corriente se lee lo que ningún cartel cuenta: oxígeno, temperatura, vida. La superficie es la portada del expediente; basta mirarla con atención para empezar a leer el estado del río. No hace falta meter la mano ni el instrumento. TRUTTA documenta estos detalles porque enseñan a mirar: a entender un río por su piel antes que por sus datos.',
  'expoalberche-horizontal-5': 'Tramo ancho y sereno del Alberche, donde el río se toma su tiempo. La corriente se extiende, se relaja y respira con calma entre las orillas. No hay urgencia ni turbulencia, solo un avance pausado. La amplitud da una sensación de descanso. || Pero esa amplitud no diluye su pureza: el agua fría sigue siéndolo aunque vaya despacio. La calma, aquí, es solvencia, no abandono; el río puede permitirse ir lento porque está sano. Lo tranquilo no siempre es lo estancado, y conviene no confundirlos. TRUTTA documenta este tramo sereno como ejemplo de que un río puede ser ancho, lento y, a la vez, perfectamente vivo.',
  'expoalberche-horizontal-6': 'La corriente dibuja la curva del valle: agua que conoce su camino mejor que cualquier mapa. El Alberche serpentea entre Ávila y Toledo sin pedir permiso ni consultar fronteras. Cada meandro responde a la pendiente, no a la administración. El trazado es viejo, seguro, propio. || Su recorrido es más antiguo que las provincias que cruza y que los nombres que les damos. El Alberche no respeta divisiones políticas: respeta la gravedad, y eso lo mantiene fresco y en movimiento. Mientras siga su curva natural, seguirá oxigenándose en cada giro. TRUTTA documenta ese trazado para recordar que el río tenía su mapa mucho antes de que nosotros dibujáramos el nuestro.',

  /* ---------- OTRAS · Alberche (carrusel) ---------- */
  'alberche-whatsapp-image-2026-06-06-at-15-17-28': 'El Alberche se abre paso entre laderas peladas, con el caudal estable y la ribera viva. Alrededor, la tierra se reseca bajo el sol; junto al agua, todo sigue verde. El río traza un corredor de vida en mitad de la aridez. El contraste entre orilla y monte es brusco y elocuente. || Mientras ese corredor verde se mantenga, el agua seguirá limpia y fría. La ribera es la última línea de defensa del cauce: filtra, sombrea y sujeta la tierra. Perderla sería el primer paso para perder el río. TRUTTA documenta esta franja viva porque es, a menudo, lo primero que desaparece cuando la presión empieza a apretar.',
  'alberche-whatsapp-image-2026-06-06-at-15-19-24': 'Los árboles se duplican en el agua quieta: el Alberche guarda su espejo intacto. La superficie devuelve el reflejo sin una sola arruga que lo rompa. La escena transmite una calma casi irreal. Esa quietud, sin embargo, no es pereza. || Es agua bien oxigenada, sin prisa pero sin estancarse, en perfecto reposo. El reflejo perfecto es señal de superficie sana: un espejo solo se forma sobre agua que se respeta a sí misma. La calma, aquí, es un signo positivo, no una alarma. TRUTTA documenta estos remansos porque enseñan a leer la quietud correcta, esa que acompaña a la pureza en lugar de delatar su ausencia.',
  'alberche-whatsapp-image-2026-06-06-at-15-30-20d': 'Solo superficie: el río respira oxígeno frío en cada rizo de la corriente. El plano se queda con el agua misma, sin contexto ni orilla. Lo que vemos es la piel del cauce, en movimiento perpetuo. Cada pliegue es un gesto de vida. || Debajo de esa piel está el frío constante que la trucha necesita para vivir. Cada onda es una bocanada del cauce: el río inspira y espira sin descanso, y por eso sigue sano. El movimiento no es decorativo, es respiración. TRUTTA documenta esta superficie viva como el signo vital más elemental: mientras el agua se rice así, el río está respirando.',
  'alberche-whatsapp-image-2026-06-06-at-15-31-44-copia': 'El cañaveral filtra la orilla, espeso, donde el agua toca la tierra. Los juncos crecen apretados en el borde, formando una franja densa y verde. Esa vegetación no está de más: hace un trabajo silencioso. Donde crece el junco, el agua suele estar sana. || La vegetación de ribera depura el agua, da sombra al cauce y sujeta la orilla contra la erosión. Arrancarla sería enfermar el río; dejarla, certificarlo: la planta y el agua se avalan mutuamente. Un cauce con cañaveral sano rara vez está enfermo. TRUTTA documenta estos bordes vegetales porque son infraestructura natural, tan útil como invisible para quien no sabe mirarla.',
  'alberche-whatsapp-image-2026-06-06-at-15-31-44': 'Piedra, planta y agua en equilibrio, cada elemento en su sitio. El cauce reúne lecho pedregoso, ribera viva y corriente fría en un mismo plano. El bioindicador más exigente vive aquí porque aquí no falta nada. Oxígeno, frío y refugio se dan juntos. || Este equilibrio no se diseña en un despacho; se respeta o se pierde. La presencia de la trucha no es un detalle pintoresco: es el resultado, comprobable, de que todo lo demás está en su sitio. Si ella vive, el sistema entero funciona. TRUTTA documenta estos tramos completos como prueba de que la salud de un río es la suma de muchas cosas pequeñas, todas a la vez.',
  'alberche-whatsapp-imagea-2026-06-06-at-15-26-45': 'El valle del Tiétar enmarca el Alberche: sierra arriba, trucha abajo. El relieve domina la escena y el río la atraviesa, fresco, en su fondo. La montaña le da la sombra y el frío que necesita. Cuenca y cauce se ven aquí como una sola unidad. || Y el río, a cambio, le devuelve vida al valle que lo alberga. Documentar uno es documentar el otro: el cauce y su cuenca son un solo expediente que no se puede partir en dos. Separarlos sería entender mal cómo funciona un río. TRUTTA documenta el conjunto —agua y montaña— porque la salud del Alberche empieza mucho antes de que el agua llegue al cauce.',

  /* ---------- OTRAS · río (carrusel) ---------- */
  'img-0046': 'El camino seco que lleva al agua: antesala árida de un río escondido. La tierra cuarteada se extiende sin anunciar lo que guarda al fondo del valle. El sendero polvoriento no promete frescor alguno. Y sin embargo, al final, hay corriente. || Llegar cuesta, y así debe ser: lo difícil de alcanzar se conserva mejor. La distancia es, a veces, la mejor protección de un río, mejor que cualquier valla o cartel. Lo que no es cómodo de visitar suele seguir intacto. TRUTTA documenta también estos accesos ingratos, porque la dificultad del camino forma parte de por qué el agua, al final, sigue limpia.',
  'img-0132': 'Niebla baja sobre la sierra: el río se intuye más que se ve, envuelto en bruma. El paisaje se difumina y el agua se confunde con el aire frío. Apenas se distingue dónde está la corriente. Todo queda velado, silencioso, suspendido. || En la bruma, el agua y el aire comparten temperatura y silencio, en una misma calma helada. El frío que envuelve el paisaje es el mismo que mantiene viva la corriente. Lo que oculta la niebla no está perdido, solo guardado del ruido. TRUTTA documenta estas mañanas veladas porque la niebla, lejos de esconder el río, lo protege: nadie molesta lo que apenas se ve.',
  'img-0137': 'El cauce serpentea entre cerros, dibujando la geografía de la España Vaciada. El río traza curvas amplias por un valle sin apenas señales humanas. Cada meandro responde al terreno, no a un plano. El paisaje es vasto, vacío y silencioso. || Donde no llega el hombre, el río escribe el mapa a su gusto, sin línea recta que lo corrija. Este trazado no obedece a ningún proyecto: obedece a la pendiente, y por eso es perfecto. La ausencia de intervención es, aquí, una forma de salud. TRUTTA documenta estos cauces libres como recordatorio de cómo se mueve un río cuando nadie le impone por dónde.',
  'img-0146': 'Aguas espejo bajo el monte: una quietud que mide, sin instrumentos, la salud del río. La superficie inmóvil refleja el relieve sin distorsión alguna. El agua está tan calmada que parece sólida. Solo el agua sana logra esa quietud. || Esa lámina lisa es señal de agua limpia y bien oxigenada, en reposo pero no muerta. La calma, aquí, es un diagnóstico favorable: solo el agua sana sabe estarse quieta sin pudrirse. El estancamiento huele; esto, no. TRUTTA documenta estos remansos porque enseñan a distinguir la quietud viva de la quietud enferma, que a primera vista se parecen.',
  'img-0156': 'Textura de agua viva: cada onda es una respiración del cauce. El plano se llena de pliegues, brillos y movimiento constante. La superficie no se detiene ni un instante. El dibujo de la luz cambia a cada segundo. || Ese dibujo cambiante oculta, debajo, una constancia química absoluta. El río se mueve sin parar precisamente para no corromperse, para renovar el oxígeno sin descanso. Bajo la superficie inquieta, la salud se mantiene fija como una firma. TRUTTA documenta esta textura como signo vital: mientras el agua se agite así, el río sigue respirando con normalidad.',
  'img-0172': 'Cantos rodados y corriente clara: el río enseña su esqueleto de piedra a través del agua. El lecho aparece nítido, redondeado, pulido por el tiempo. Nada enturbia la visión del fondo. Es la imagen más directa de un cauce limpio. || El lecho visible es la prueba más inmediata de pureza: sin turbidez, no hay nada que esconder. Cada piedra pulida cuenta siglos de agua paciente trabajando sin prisa. El río lleva aquí más tiempo del que duran nuestras decisiones. TRUTTA documenta el fondo a la vista porque es, en sí mismo, un certificado geológico de que el agua sigue haciendo bien su trabajo.',
  'img-0240': 'Arbolado a ras del agua: la ribera protege lo que fluye, inclinándose sobre la corriente. Los árboles cubren el cauce y filtran la luz que llega al agua. La sombra mantiene fresca la superficie. La frontera entre bosque y río casi desaparece. || La sombra de los árboles enfría la corriente y la mantiene a la temperatura que exige la trucha. Bosque y río se cuidan mutuamente sin contrato, en una alianza antigua. El archivo solo puede constatar ese pacto, no inventarlo ni mejorarlo. TRUTTA documenta estas riberas arboladas porque son, literalmente, el aire acondicionado natural del río, y lo primero que se tala.',
  'img-0264': 'El valle abre paso al caudal: líneas de tierra abajo, lámina de agua en medio. El paisaje se extiende amplio, con el río como única presencia móvil. La escena es vasta y serena. La amplitud no le resta importancia al agua, al contrario. || En medio de tanta tierra quieta, el agua es lo único que se mueve, lo único vivo, lo único que merece vigilancia. La amplitud del paisaje subraya la importancia del río en lugar de diluirla. Quita el agua y queda solo terreno; deja el agua y hay un sistema entero. TRUTTA documenta estos planos amplios para situar el río en su contexto: pequeño en el encuadre, esencial en el valle.',
  'img-0281': 'Orilla de roca, agua transparente: aquí el lecho no esconde nada. La piedra de la orilla se sumerge y se ve, sin sombra ni turbidez. El agua deja pasar la luz hasta el fondo. La claridad ocupa todo el plano. || La transparencia total es el sello del río sano, el más fácil de leer. Donde se ve cada piedra del fondo, no ha entrado contaminante alguno en el agua. La claridad funciona como una declaración jurada que no admite falsificación. TRUTTA documenta estas orillas limpias porque la transparencia es la prueba más barata y más fiable de todas: solo hay que mirar.',
  'img-0285': 'Piedra mojada y reflejo: el borde donde tierra y río pactan su frontera. La línea de orilla aparece húmeda, brillante, a medio camino entre lo sólido y lo líquido. Ni del todo agua ni del todo roca. En ese margen pasa más de lo que parece. || En ese margen anfibio se concentra buena parte de la vida del cauce, escondida a simple vista. Las fronteras del río no son límites muertos: son las zonas donde más cosas ocurren a la vez. Lo que parece un simple borde es, en realidad, el lugar más activo. TRUTTA documenta estas orillas porque ahí, en el roce entre agua y tierra, se juega buena parte de la salud del río.',
  'img-0287': 'Bloques en la corriente: el agua los pule sin prisa, durante siglos. Las rocas, grandes y redondeadas, parten el cauce y lo obligan a rodearlas. Cada una lleva ahí más tiempo del que imaginamos. El agua las trabaja sin descanso ni ruido. || Cada roca redondeada es un reloj geológico, prueba de que el río lleva aquí más de lo que duran nuestros planes. La paciencia del agua siempre gana: ablanda la piedra sin levantar la voz. Lo que parece inmóvil está siendo esculpido lentamente. TRUTTA documenta estos bloques como recordatorio de escala: el río mide su obra en milenios, y conviene no olvidarlo al decidir su futuro.',
  'img-0307': 'Una figura ante el río: la huella humana mínima, presente pero quieta. Alguien observa la corriente desde la orilla, sin entrar, sin tocar. La escala humana aparece, por fin, en el encuadre. Estar presente sin pisar es toda la relación admisible. || Mirar sin alterar es la única forma de relación que TRUTTA admite con el cauce. El testigo documenta; no interviene: su trabajo consiste en desaparecer de la escena que registra. La mejor visita es la que no deja rastro. TRUTTA documenta esta presencia discreta como modelo de conducta: el río se puede contemplar entero, siempre que uno se quede en la orilla.',
  'img-0365': 'Lecho pedregoso bajo agua clara: oxígeno, frío y pureza en estado bruto. El fondo de cantos se ve nítido a través de la corriente. La transparencia delata un agua de calidad excepcional. Es un tramo de los que ya casi no quedan. || El fondo visible certifica lo que la trucha confirma con su sola presencia. Aguas así quedan ya muy pocas, y este expediente las cuenta una a una, con cuidado. Cada tramo limpio es una excepción que merece ser nombrada antes de que deje de serlo. TRUTTA documenta estos lechos transparentes con la urgencia de quien registra algo en vías de volverse raro.',
  'img-0405': 'El tajo de roca sobre el cauce: la cuenca tallada por el agua, milímetro a milímetro. La pared vertical se alza junto a la corriente, abierta por el río a lo largo de eras. La piedra cortada cuenta una historia muy larga. El agua escribió esto sin prisa. || La pared es la firma del río en la roca, paciente e implacable. Lo que el agua tardó milenios en abrir no debería cerrarse en una sola generación humana. La geología no entiende de prisas ni de plazos políticos. TRUTTA documenta estas paredes para imponer perspectiva: ante una obra del agua medida en eras, nuestras decisiones de unas décadas resultan diminutas.',
  'img-0468': 'Caserío asomado al agua: lo construido vigila, de lejos, al río. Las casas se alinean en la ladera, manteniendo una distancia prudente con la orilla. No invaden el cauce, pero tampoco le dan la espalda. La convivencia parece, aquí, bien medida. || Esa distancia —ni demasiado cerca ni del todo de espaldas— es exactamente la que defiende TRUTTA. Convivir con el río sin asfixiarlo es posible, y este caserío lo demuestra. Ni colonizar la orilla ni ignorar el agua: mantener el respeto del margen. TRUTTA documenta este equilibrio como modelo de asentamiento: pueblos que viven del río precisamente porque saben no apretarlo demasiado.',
};

/** Fallback copy (only if an id isn't catalogued). */
export const DEFAULT_TEXT =
  `La trucha común (Salmo trutta) es el organismo indicador más fiable para evaluar la salud de los
ecosistemas acuáticos de aguas frías. Su presencia confirma oxigenación excepcional, temperatura
estable y ausencia total de contaminantes orgánicos o metales pesados. || Cada fotografía de este
archivo documenta un tramo de los ríos de la España Vaciada y el estado de su agua a través de su
habitante más exigente, registrado sin pisar la orilla ni alterar la corriente.`;

/** Strip a manifest id out of an optimized image URL (…/<id>-full.webp). */
export const idFromUrl = (url = '') =>
  String(url).split('/').pop().replace(/-(full|thumb)\.webp$/i, '');

/** Raw "left || right" text for an id (or the default). */
export const textFor = (id) => PHOTO_TEXT[id] || DEFAULT_TEXT;

/** [leftColumn, rightColumn] paragraphs for the detail overlay. */
export const textCols = (id) => {
  const [a, b] = textFor(id).split('||').map((s) => s.trim());
  return [a, b || a];
};

/** First sentence of the left paragraph — short caption for the recorrido. */
export const leadFor = (id) => {
  const left = textFor(id).split('||')[0].trim();
  const m = left.match(/^.*?\.(?:\s|$)/);
  return m ? m[0].trim() : left;
};

/** 1-based archive number for a photo id (0 if not catalogued). */
export const numFor = (id) => ARCHIVE.indexOf(id) + 1;
